=== OpenTechStrategies/gandhi/lib/api/schemas/cycle.json
{
  "id": "cycle",
  "$schema": "http://json-schema.org/draft-04/schema",
  "required": [
    "title"
  ],
  "type":"object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "open": {
      "type": ["boolean", "date"],
      "default": true
    },
    "close": {
      "type": ["boolean", "date"],
      "default": false
    },
    "description": {
      "type": "string",
      "default": ""
    },
    "events": {
      "type": "object",
      "default": {
        "open": {
          "id": "open",
          "title": "Application Window Opened",
          "messages": [
            "Applications are not yet being accepted.",
            "Applications are being accepted."
          ],
          "conditions": [
            [
              {
                "name": "open",
                "options": {}
              }
            ]
          ],
          "listeners": []
        },
        "close": {
          "id": "close",
          "title": "Application Window Closed",
          "messages": [
            "Applications are still open.",
            "Applications are no longer being accepted."
          ],
          "conditions": [
            [
              {
                "name": "close",
                "options": {}
              }
            ]
          ],
          "listeners": []
        }
      },
      "additionalProperties": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "object",
            "required": [
              "id",
              "title"
            ],
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": "string",
                "constant": {"$data": "0"}
              },
              "title": {
                "type": "string"
              },
              "messages": {
                "type": "array",
                "default": [
                  "",
                  ""
                ],
                "items": {
                  "type": "string"
                },
                "minItems": 2,
                "maxItems": 2
              },
              "conditions": {
                "type": "array",
                "default": [],
                "items": {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "object",
                    "required": ["name"],
                    "additionalProperties": false,
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "options": {
                        "type": "object",
                        "additionalProperties": true,
                        "default": {}
                      }
                    }
                  }
                }
              },
              "listeners": {
                "type": "array",
                "default": [],
                "items": {
                  "type": "object",
                  "required": ["name"],
                  "additionalProperties": false,
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "options": {
                      "type": "object",
                      "additionalProperties": true,
                      "default": {}
                    }
                  }
                }
              }
            }
          }
        ]
      }
    },
    "root": {
      "type": "string",
      "default": "start"
    },
    "flow": {
      "type": "object",
      "default": {
        "start": {
          "id": "start",
          "title": "Start",
          "description": "Start your application!",
          "visible": [
            "applicant"
          ],
          "lock": {
            "open": [
              "open"
            ],
            "close": [
              "submit",
              "archive",
              "close"
            ]
          },
          "component": {
            "name": "start",
            "options": {
              "next": null,
              "role": "applicant",
              "permissions": {
                "write": [
                  "applicant"
                ]
              }
            }
          },
          "next": []
        }
      },
      "additionalProperties": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "object",
            "required": ["id", "title", "component"],
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": "string",
                "constant": {"$data": "0"}
              },
              "title": {
                "type": "string"
              },
              "description": {
                "type": "string",
                "default": ""
              },
              "visible": {
                "type": "array",
                "default": [],
                "items": {
                  "type": "string"
                }
              },
              "lock": {
                "type": "object",
                "additionalProperties": false,
                "default": {
                  "open": [],
                  "close": []
                },
                "properties": {
                  "open": {
                    "type": "array",
                    "default": [],
                    "items": {
                      "type": "string"
                    }
                  },
                  "close": {
                    "type": "array",
                    "default": [],
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              "component": {
                "type": "object",
                "required": ["name"],
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "options": {
                    "type": "object",
                    "additionalProperties": true
                  }
                }
              },
              "next": {
                "type": "array",
                "default": [],
                "items": {
                  "type": "string"
                }
              }
            }
          }
        ]
      }
    },
    "roles": {
      "type": "object",
      "default": {
        "applicant": {
          "id": "applicant",
          "title": "Applicant",
          "visible": [
            "applicant"
          ],
          "assignable": [
            "applicant"
          ]
        }
      },
      "additionalProperties": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "object",
            "required": [
              "id",
              "title",
              "visible",
              "assignable"
            ],
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": "string",
                "constant": {"$data": "0"}
              },
              "title": {
                "type": "string"
              },
              "visible": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "assignable": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        ]
      }
    },
    "status": {
      "type": "string",
      "default": "draft",
      "enum": [
        "draft",
        "active",
        "archived"
      ]
    },
    "statuses": {
      "type": "object",
      "default": {
        "active": {
          "id": "active",
          "title": "Active"
        },
        "accepted": {
          "id": "accepted",
          "title": "Accepted"
        },
        "rejected": {
          "id": "rejected",
          "title": "Rejected"
        },
        "archived": {
          "id": "archived",
          "title": "Archived"
        }
      },
      "additionalProperties": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "object",
            "required": ["id", "title"],
            "additionalProperties": true,
            "properties": {
              "id": {
                "type": "string",
                "constant": {"$data": "0"}
              },
              "title": {
                "type": "string"
              }
            }
          }
        ]
      }
    },
    "users": {
      "type": "object",
      "default": {},
      "additionalProperties": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "object",
            "additionalProperties": true,
            "required": [
              "id",
              "role"
            ],
            "properties": {
              "id": {
                "type": "string",
                "constant": {"$data": "0"}
              },
              "role": {
                "type": "string"
              }
            }
          }
        ]
      }
    },
    "updated": {
      "type": "date"
    },
    "created": {
      "type": "date"
    }
  }
}

=== OpenTechStrategies/gandhi/setup/db/cycles.json
[
  {
    "id": "128f2348-99d4-40a1-b5ab-91d9019f272d",
    "title": "Sample Application Cycle",
    "description": "This application cycle is just a sample.",
    "events": {
      "open": {
        "id": "open",
        "title": "Application Window Opened",
        "messages": [
          "Applications are not yet being accepted.",
          "Applications are being accepted."
        ],
        "conditions": [
          [
            {
              "name": "date",
              "options": {
                "mode": "after",
                "date": {
                  "$reql_type$": "TIME",
                  "epoch_time": 1405203171.364,
                  "timezone": "+00:00"
                }
              }
            }
          ]
        ],
        "listeners": []
      },
      "warning": {
        "id": "warning",
        "title": "Application Window Closing Soon",
        "messages": [
          "This project is not in jeopardy of missing the application window.",
          "This project is in jeopardy of missing the application window."
        ],
        "conditions": [
          [
            {
              "name": "date",
              "options": {
                "mode": "after",
                "date": {
                  "$reql_type$": "TIME",
                  "epoch_time": 1405803171.364,
                  "timezone": "+00:00"
                }
              }
            },
            {
              "name": "regex",
              "options": {
                "regex": "^complete$",
                "invert": true,
                "pointer": "/flow/stages/submission/status"
              }
            }
          ]
        ],
        "listeners": [
          {
            "name": "email",
            "options": {
              "value": true,
              "roles": [
                "applicant",
                "advisor"
              ],
              "template": "Don't get left behind!"
            }
          }
        ]
      },
      "close": {
        "id": "close",
        "title": "Application Window Closed",
        "messages": [
          "Applications are still open.",
          "Applications are no longer being accepted."
        ],
        "conditions": [
          [
            {
              "name": "date",
              "options": {
                "mode": "after",
                "date": {
                  "$reql_type$": "TIME",
                  "epoch_time": 1406203171.364,
                  "timezone": "+00:00"
                }
              }
            }
          ]
        ],
        "listeners": []
      },
      "complete": {
        "id": "complete",
        "title": "Application Complete",
        "messages": [
          "The application is not yet complete.",
          "The application is complete."
        ],
        "conditions": [
          [
            {
              "name": "regex",
              "options": {
                "regex": "^complete$",
                "pointer": "/flow/stages/start/status"
              }
            },
            {
              "name": "regex",
              "options": {
                "regex": "^complete$",
                "pointer": "/flow/stages/team/status"
              }
            },
            {
              "name": "regex",
              "options": {
                "regex": "^complete$",
                "pointer": "/flow/stages/application/status"
              }
            }
          ]
        ],
        "listeners": []
      },
      "submit": {
        "id": "submit",
        "title": "Officially Submitted",
        "messages": [
          "This project has not yet been submitted.",
          "This project has been submitted."
        ],
        "conditions": [
          [
            {
              "name": "regex",
              "options": {
                "regex": "^complete$",
                "pointer": "/flow/stages/submission/status"
              }
            }
          ]
        ],
        "listeners": []
      },
      "report": {
        "id": "report",
        "title": "Report Submitted",
        "messages": [
          "This project's report has not yet been submitted.",
          "This project's report has been submitted."
        ],
        "conditions": [
          [
            {
              "name": "regex",
              "options": {
                "regex": "^complete$",
                "pointer": "/flow/stages/report/status"
              }
            }
          ]
        ],
        "listeners": []
      },
      "archive": {
        "id": "archive",
        "title": "Archived",
        "messages": [
          "This project is not archived.",
          "This project has been archived."
        ],
        "conditions": [
          [
            {
              "name": "regex",
              "options": {
                "regex": "^archived$",
                "pointer": "/status"
              }
            }
          ]
        ],
        "listeners": []
      },
      "accept": {
        "id": "accept",
        "title": "Accepted",
        "messages": [
          "This project has not yet been accepted.",
          "This project has been accepted."
        ],
        "conditions": [
          [
            {
              "name": "regex",
              "options": {
                "regex": "^accepted$",
                "pointer": "/status"
              }
            }
          ]
        ],
        "listeners": []
      },
      "reject": {
        "id": "reject",
        "title": "Rejected",
        "messages": [
          "This project is not rejected.",
          "This project has been rejected."
        ],
        "conditions": [
          [
            {
              "name": "regex",
              "options": {
                "regex": "^rejected$",
                "pointer": "/status"
              }
            }
          ]
        ],
        "listeners": []
      }
    },
    "root": "start",
    "flow": {
      "start": {
        "id": "start",
        "title": "Start",
        "description": "Start your application!",
        "visible": {
          "staff": true,
          "applicant": true,
          "advisor": true,
          "reviewer": true
        },
        "component": {
          "name": "start",
          "status": "active",
          "options": {
            "next": "team",
            "role": "applicant",
            "permissions": {
              "write": [
                "staff",
                "applicant"
              ]
            }
          }
        },
        "next": [
          "team"
        ]
      },
      "team": {
        "id": "team",
        "title": "Team",
        "description": "Build your team by adding collaborators to your application.",
        "visible": {
          "staff": true,
          "applicant": true,
          "advisor": true,
          "reviewer": true
        },
        "component": {
          "name": "users",
          "options": {
            "next": "application",
            "roles": [
              "applicant",
              "advisor"
            ],
            "permissions": {
              "assign": [
                "staff",
                "applicant"
              ],
              "remove": [
                "staff",
                "applicant"
              ]
            }
          }
        },
        "next": [
          "supplement"
        ]
      },
      "application": {
        "id": "application",
        "title": "Application Form",
        "description": "Fill out our online application form.",
        "visible": {
          "staff": true,
          "applicant": true,
          "advisor": true,
          "reviewer": true
        },
        "component": {
          "name": "form",
          "options": {
            "next": "assignment",
            "permissions": {
              "read": [
                "staff",
                "applicant",
                "advisor",
                "reviewer"
              ],
              "write": [
                "staff",
                "applicant"
              ]
            }
          }
        },
        "next": [
          "submission"
        ]
      },
      "submission": {
        "id": "submission",
        "title": "Official Submission",
        "description": "Officially submit your application. Once submitted, your application can no longer be edited.",
        "visible": {
          "staff": true,
          "applicant": true,
          "advisor": true,
          "reviewer": true
        },
        "component": {
          "name": "form",
          "options": {
            "next": "acknowledgment",
            "permissions": {
              "read": [
                "staff",
                "applicant",
                "advisor",
                "reviewer"
              ],
              "write": [
                "staff",
                "applicant"
              ]
            }
          }
        },
        "next": [
          "acknowledgment"
        ]
      },
      "acknowledgment": {
        "id": "acknowledgment",
        "title": "Submission Acknowledgment",
        "description": "This page acknowledges that the application was received.",
        "visible": {
          "applicant": true,
          "advisor": true
        },
        "component": {
          "name": "message",
          "options": {
            "default": {
              "default": "You have not yet submitted your application.",
              "roles": {}
            },
            "open": {
              "default": "Thank you for submitting your application! It will be reviewed shortly.",
              "roles": {}
            },
            "close": {
              "default": "Thank you for submitting your application! A funding decision has been made.",
              "roles": {}
            },
            "permissions": {
              "write": [
                "staff"
              ]
            }
          }
        },
        "next": [
          "assignment"
        ]
