=== OpenTechStrategies/gandhi/lib/api/schemas/files.json
{
  "id": "file",
  "type":"object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "required": [
    "name",
    "mimetype",
    "encoding",
    "path",
    "extension",
    "size"
  ],
  "additionalProperties": false,
  "properties":{
    "created": {
      "type": "date"
    },
    "user_id": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "default": ""
    },
    "mimetype": {
      "type": "string",
      "default": ""
    },
    "encoding": {
      "type": "string",
      "default": ""
    },
    "path": {
      "type": "string",
      "default": ""
    },
    "extension": {
      "type": "string",
      "default": ""
    },
    "size": {
      "type": "number"
    },
    "updated": {
      "type": "date"
    },
    "lock": {
      "type": "boolean",
      "default": false
    }
  }
}

=== OpenTechStrategies/gandhi/test/fixtures/db/files.json
[{
	"mimetype": "application/pdf",
	"updated": 1413179110.813,
	"user_id": "e3195f3f-94d8-41c8-a072-06d1aec2bb49",
	"name": "Anna Ver Beek.pdf",
	"extension": "pdf",
	"encoding": "7bit",
	"lock": false,
	"created": 1413179110.813,
	"path": "./test/fixtures/uploads/e4ada0dca20f5d3ec759c1a430b376c3.pdf",
	"id": "17f8d1d1-05a9-4c4b-94a5-db1da3101833",
	"size": 9502
}, {
	"mimetype": "application/pdf",
	"updated": 1413168466.098,
	"user_id": "cf237901-2890-439f-add3-dc641b867459",
	"name": "Exploring the effects of caffeine addiction on contemporary architecture.pdf",
	"extension": "pdf",
	"encoding": "7bit",
	"lock": false,
	"created": 1413168466.098,
	"path": "./test/fixtures/uploads/88f71add75f29e624675c2cb557ac669.pdf",
	"id": "4f406e9f-a1ba-4b7b-9aae-c37b42a0cc03",
	"size": 11791
}, {
	"mimetype": "application/pdf",
	"updated": 1413179144.976,
	"user_id": "e3195f3f-94d8-41c8-a072-06d1aec2bb49",
	"name": "Somebody Else.pdf",
	"extension": "pdf",
	"encoding": "7bit",
	"lock": false,
	"created": 1413179144.976,
	"path": "./test/fixtures/uploads/765d9d3c9328d06f0ebb388fa6076852.pdf",
	"id": "5cd2f952-0665-4a96-ac7d-7d44fa323fbe",
	"size": 10025
}, {
	"mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"updated": 1413168482.337,
	"user_id": "cf237901-2890-439f-add3-dc641b867459",
	"name": "Template-Budget-Seed.xlsx",
	"extension": "xlsx",
	"encoding": "7bit",
	"lock": false,
	"created": 1413168482.337,
	"path": "./test/fixtures/uploads/75c35e748a4760bcd1acf900022e5b38.xlsx",
	"id": "5fac8e78-9f7b-48dd-982d-1f129e411a98",
	"size": 12422
}, {
	"mimetype": "application/pdf",
	"updated": 1413179073.384,
	"user_id": "e3195f3f-94d8-41c8-a072-06d1aec2bb49",
	"name": "The influence of language on wealth and poverty .pdf",
	"extension": "pdf",
	"encoding": "7bit",
	"lock": false,
	"created": 1413179073.384,
	"path": "./test/fixtures/uploads/aa192c96ff6ef986b64f67a3ab776595.pdf",
	"id": "8c0895ab-a619-45a2-b9d3-1a88700b83c1",
	"size": 12639
}, {
	"mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"updated": 1413178975.385,
	"user_id": "e3195f3f-94d8-41c8-a072-06d1aec2bb49",
	"name": "Template-Budget-Seed.xlsx",
	"extension": "xlsx",
	"encoding": "7bit",
	"lock": false,
	"created": 1413178975.385,
	"path": "./test/fixtures/uploads/37a6289ea42d1cd6117249c74af19bdd.xlsx",
	"id": "bd382550-e810-438d-b2b6-a7268bab5d03",
	"size": 12422
}, {
	"mimetype": "application/pdf",
	"updated": 1413168422.583,
	"user_id": "cf237901-2890-439f-add3-dc641b867459",
	"name": "Sol\u00e8ne.pdf",
	"extension": "pdf",
	"encoding": "7bit",
	"lock": false,
	"created": 1413168422.583,
	"path": "./test/fixtures/uploads/e9f1597863ef6f7375908b7aacccf126.pdf",
	"id": "da111093-6246-4245-921b-0f1e8da7e205",
	"size": 11453
}]
