=== OpenTechStrategies/gandhi/lib/api/schemas/user.json
{
  "id": "user",
  "type":"object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "required": [
    "email"
  ],
  "additionalProperties": false,
  "properties":{
    "admin": {
      "type": "boolean",
      "default": false
    },
    "created": {
      "type": "date"
    },
    "email": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "default": ""
    },
    "password": {
      "type": "string",
      "minLength": 4
    },
    "recovery_token": {
      "type": ["null","string"],
      "default": null
    },
    "updated": {
      "type": "date"
    }
  }
}

=== OpenTechStrategies/gandhi/test/fixtures/db/users.json
[
  {
    "id": "72e7f9a1-614d-423e-8273-1194932f8718",
    "admin": false,
    "password": "c2NyeXB0AA8AAAAIAAAAAazOoRBesUNvcjIY6X2zSkOcY7LfHDj1ZNDK94tbdN3L6oG9bIi9jm4qsG2sAuEpffBpb8XuEATpReG5YIt1vL7dwlMttPrzGFq1EEKM4wbU",
    "recovery_token": null,
    "email": "michael.douglas@test.gandhi.io",
    "name": "Michael Douglas",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  },
  {
    "id": "f6826282-1ffb-453d-8804-6b2921e6807f",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAAe6TqnGT43ChQ332QjkUCCHMYgXet95V5NlL3cw7xyZCf3P/OclO9vjqL1/QE+E42gKyCxWj2571hs/RrkBf+LCmpVIuhRIMhxYRUFwV9qW4",
    "recovery_token": null,
    "email": "matt.shafer@test.gandhi.io",
    "name": "Matt Shafer",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  },
  {
    "id": "3cd2dc98-e280-4e72-a437-9a916d98b636",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAAfJfxQEzHBLEeh3eU5cNm3GkKHmAroIKbVQQl9KEFE7CmcbnNjKrAuahB0R5WrCjyGhV3ygzIaU2NhBxIScoQPG7wJP/N4nW91BNrPm4xue/",
    "recovery_token": null,
    "email": "eric.jensen@test.gandhi.io",
    "name": "Eric Jensen",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  },
  {
    "id": "5a3cf444-9d87-4125-8026-2d5ffb834676",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAATZ/fO+WCFdWZ8CVN/tavTXX0WcFBCQDtzGZn6/nv0d6IBW8geom2/fQTVb4T0oPYd9Ze4baEKAWqU2PHU6oxBqhmj+kXf1CyBWTsCOUBFfP",
    "recovery_token": null,
    "email": "jon.ramos@test.gandhi.io",
    "name": "Jon Ramos",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  },
  {
    "id": "82b08fd0-b93d-4169-a0bf-b25823077adb",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAAe/1UjL3qtgcQjKxswA1spbRkYInvpGu62YdiG2zfRjgUrxiI7KNWVBJkjlLEYUaSqputmF+RH+ugwQvu9UmZOU2cLMc5bNAxNA+ML/p1XXr",
    "recovery_token": null,
    "email": "mark.boerneke@test.gandhi.io",
    "name": "Mark Boerneke",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  },
  {
    "id": "847e085b-df0e-4dc7-9cbf-d485d6e2de96",
    "admin": false,
    "password": "c2NyeXB0AA8AAAAIAAAAAfXCOXrKklbdOscJOZcTgvn94drsvqOu5tf/fc7/AV6RrUHMJr1HvcuNUD2gbCTXZ9RYPbpX9liyh5FoWb9nVzsUx+luLAX42wsm1ukOBLb5",
    "recovery_token": "c2NyeXB0AA4AAAAIAAAAARhyUZ+MHlSmwgVs1o7YLiDkNebjRGOKioaoaZ6TPdOuZx7u98nhtEaxeMhr8qaBscAqmvqLhhAA8V7vILvdLMC7oYEwB6cedX/AN89SvKLO",
    "email": "dustin.towery@test.gandhi.io",
    "name": "Dustin Towery",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  },
  {
    "id": "84fbaa78-54b0-42fc-9754-c9ea7dc24538",
    "admin": false,
    "password": "c2NyeXB0AA4AAAAIAAAAATA+dYEi/gYuTrBfkz2/kXbgLlh+H5d96Tdxab0+sZeupIuPLZG9SCY+FgW8OXUXL4KlJLOsKwoA3V2GYnfpp7Yt5OHDsfbHkDw+2XjL35T5",
    "recovery_token": "c2NyeXB0AA8AAAAIAAAAAUEmpTp68mfzMIQMlkUd3zqd4SZaQe1xDm32Dk/yH2dZ0GkrciH6KX6j9VAIMqgyuNuGZwapU+lj5h8QDOjr6YMHtT19dtrwE7RlNcwTjd1d",
    "email": "tim.marcacci@test.gandhi.io",
    "name": "Tim Marcacci",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  },
  {
    "id": "a5901ab6-bf17-49cd-981d-c25875aec8e9",
    "admin": true,
    "password": "c2NyeXB0AA4AAAAIAAAAAXJUMPjPphkqlfeJ5X7Kx9EyRGQy/f74JOAS5zzEOVGsOL/Z2i/BjMz6rOn5pA2bIqyKcZfc8ipslSSZahvLteZ2ycnl3gSf2lqzdklnZyMA",
    "recovery_token": null,
    "email": "mike.marcacci@test.gandhi.io",
    "name": "Mike Marcacci",
    "created": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"},
    "updated": { "$reql_type$": "TIME", "epoch_time": 1407029321882, "timezone": "+00:00"}
  }
]
